### ISSUE TITLE
How exactly do you build this?

### ISSUE THREAD

**Issue by Nobody1902** [qyx22122/Tibi_OS#3]
I just can't build it.
`cargo run` throws an error.
`cargo build` works, but where is the `.bin` file?

**Comment by qyx22122** [comment]
cargo run should work
.bin is in target/x86_64-Tibi_OS/debug/

**Comment by Nobody1902** [comment]
Why don't you create a docker container so that anyone can build it?
`cargo run` errors at line "bootimage runner..."
I'm using qemu as the emulator, so the `.bin` file is important. I didn't see any.
